apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini-project1
  template:
    metadata:
      labels:
        app: mini-project1
    spec:
      containers:
      - name: regression-model
        image: gaurav98094/project1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
