apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-deployment
spec:
  selector:
    matchLabels:
      app: second-app
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: node-website
          image: gaurav98094/k8sapp
          livenessProbe:
            httpGet:
             path: /
             port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5